[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.mod-1-primo-test-metrogauss-img]
script_runner = "@shell"
script = '''
cargo run --package mod_1 \
--example metropolis-gauss
'''
#command = "cargo"
#args = [
#    "run", "--package", "mod_1", "--example", "metropolis-gauss", "--",
#    "1000",
#    "--seed", "42",
#    "--mu", "10",
#    "--sigma", "1",
#    "--x0", "0",
#    "--delta", "1",
#    "--plot", "mod_1/img/primo_test_metrogauss"
#]